Web server
jeelabs/el-client pull request #21
Opened 2016-09-27 05:48 UTC by cskarai

This is the client code for web server.

I also had to modify the default 128 byte buffer to allocate it dynamically. 128 byte is not enough for form submission if there are plenty of controls.  User can set the required buffer size.

2016-09-28 02:03 UTC, tve commented
Thank you! I want to get PR #20 is first so I get the docs in the right place. I don't think there will be too much conflict.

2016-10-01 06:41 UTC, cskarai commented
Merged the pull request to the latest branch.

Also replaced socket cmd constant 30 to 40, not to interfere with web server. 

This pull request doesn't contain the API docs of web server. Since the last change API docs were added, and it means, that web server should also contain this to be consistent with other parts of the code.

I plan to add docs

2016-10-01 19:04 UTC, tve commented on ELClient/ELClient.cpp
> +      if( callbackPacketHandler(packet) )
why can't you fit your stuff into the CMD_RESP_CB?

2016-10-02 05:35 UTC, tve requested changes
I'd really like to simplify things a bit so the dispatch in ELClient doesn't need to change. Also, I don't understand the need to chain callback handlers. Let me know whether you want to make the changes or whether you want me to take it from here.

2016-10-02 05:35 UTC, tve commented on ELClient/ELClientWebServer.cpp
> +        memcpy(id, idPtr, idLen);
why do you copy the id as opposed to just passing idPtr to the callback?

2016-10-02 05:35 UTC, tve commented on ELClient/ELClientWebServer.cpp
> +void ELClientWebServer::processPacket(ELClientPacket *packet)
why do you need to process a packet as opposed to just a response, which would fit much better into the ElClient library dispatch structure?

2016-10-02 05:35 UTC, tve commented on ELClient/ELClientWebServer.cpp
> +ELClientWebServer::ELClientWebServer(ELClient* elc) :_elc(elc),handlers(0), arg_ptr(0) {
Why do you need to support multiple ElClientWebServer instances? Why is a singleton not sufficient? Then you would not need this chaining of callback handlers if I understand correctly.

2016-10-02 05:35 UTC, tve commented on ELClient/ELClientWebServer.cpp
> +          memcpy(arg_ptr, idPtr + 2 + nameLen, valueLen);
same question as above: why do you copy?

2016-10-02 05:35 UTC, tve commented on ELClient/ELClientWebServer.h
> +typedef void (*WebServerCallback)(WebServerCommand command, char * data, int dataLen);
What do you think of breaking the 4 different callbacks out into 4 functions as opposed to jamming everything into one callback?

2016-10-02 05:35 UTC, tve commented on ELClient/ELClientWebServer.cpp
> +  _elc->Request(CMD_WEB_DATA, 100, 255);     // 255 arguments (can't foretell, so use maximum)
Would be best to define some notion of "varargs" and use a named constant for 255 and the also in esp-link... Basically make 255 args mean "varargs" officially.

2016-10-02 05:35 UTC, tve commented on ELClient/examples/webserver_controls/LedPage.ino
> +void ledHtmlCallback(WebServerCommand command, char * data, int dataLen)
This would be nicer if there were 4 separate callback functions...

2016-10-02 05:35 UTC, tve commented on ELClient/examples/webserver_controls/webserver_controls.ino
> +  if ((millis()-last) > 4000) {
The new ELClient library does this differently. Please see https://github.com/jeelabs/el-client/blob/master/ELClient/ELClient.h#L58-L74

2016-10-02 20:50 UTC, cskarai commented on ELClient/ELClient.cpp
> +      if( callbackPacketHandler(packet) )
This is not a response. It's more like a topic to subscribe.
I didn't use this because of its name.

2016-10-02 20:57 UTC, cskarai commented on ELClient/ELClientWebServer.cpp
> +ELClientWebServer::ELClientWebServer(ELClient* elc) :_elc(elc),handlers(0), arg_ptr(0) {
There's one WebServer, but I let other handlers (RTC time or some), which may use the very same callback. This is why shortcutting to web-server is not good.

2016-10-02 20:58 UTC, cskarai commented on ELClient/ELClientWebServer.cpp
> +        memcpy(id, idPtr, idLen);
The terminating 0 is missing. The final solution would be very-very complex. Do this here, add the terminating 0, call the callback.

2016-10-02 20:59 UTC, cskarai commented on ELClient/ELClientWebServer.cpp
> +          memcpy(arg_ptr, idPtr + 2 + nameLen, valueLen);
terminating 0

2016-10-02 21:03 UTC, cskarai commented
I'll rework the code based on your suggestion and add API docs.

Questions to answer (ELClient):
- handle ESP REQUEST-> MCU RESPONSE architecture, which is opposite of the current one
- handle variable size of buffer as 128 is pretty small

No other changes required for ELClient.

2016-10-05 05:27 UTC, cskarai commented on ELClient/ELClientWebServer.cpp
> +  _elc->Request(CMD_WEB_DATA, 100, 255);     // 255 arguments (can't foretell, so use maximum)
Done.

2016-10-05 05:27 UTC, cskarai commented on ELClient/ELClientWebServer.h
> +typedef void (*WebServerCallback)(WebServerCommand command, char * data, int dataLen);
Done.

2016-10-05 05:27 UTC, cskarai commented on ELClient/examples/webserver_controls/LedPage.ino
> +void ledHtmlCallback(WebServerCommand command, char * data, int dataLen)
Done.

2016-10-05 05:28 UTC, cskarai commented on ELClient/examples/webserver_controls/webserver_controls.ino
> +  if ((millis()-last) > 4000) {
Done.

2016-10-05 05:28 UTC, cskarai commented
Code modified.

2016-10-08 15:31 UTC, cskarai commented
Ready for review.

2016-10-23 05:39 UTC, merged